version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    environment:
      - PYTHONUNBUFFERED=1
      - MONGODB_URL=mongodb://dpy:password@db:27017/dpy_official?authSource=admin
  
  db:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: dpy
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: dpy_official
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
