version: '3.8'
services:
  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://dpy:password@db:5432/dpy_official
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: dpy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dpy_official
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
